version: "3.9"

services:
  backend:
    build: ./backend
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 8000
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - mern-net

  frontend:
    build:
      context: .                # 👈 switch to root so we can access ./nginx/
      dockerfile: ./frontend/Dockerfile
      args:
        REACT_APP_BASE_URL: ${REACT_APP_BASE_URL:-/api}
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - mern-net
  seed:
    build: ./backend
    command: npm run seed
    env_file: .env
    depends_on:
      - backend
    networks:
      - mern-net

networks:
  mern-net:
    driver: bridge

